SQLALCHEMY_DATABASE_URI = 'postgresql://docker:docker@postgres:5432/rr_logs'
SQLALCHEMY_TRACK_MODIFICATIONS = True
REDIS_HOST = 'redis'
RQ_REDIS_URL = 'redis://redis:6379/0'
HOST = '0.0.0.0'
PORT = 5000
DEBUG = True

TOKEN_EXPIRATION = 604800
NO_SONG_NAME = 'NO_SONG'
CHECKING_DELAY = 6
GET_SONG_TRIES = 1
TTL_IF_NO_SONG = 2

SECRET_KEY = '8dbf3f3a5436ca63'