"""empty message

Revision ID: 4f2ff3e55345
Revises: 668cb56c328a
Create Date: 2017-11-20 13:16:34.050422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2ff3e55345'
down_revision = '668cb56c328a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cdns', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cdns', 'is_active')
    # ### end Alembic commands ###
