"""empty message

Revision ID: 668cb56c328a
Revises: cc12ac692830
Create Date: 2017-11-17 15:18:33.828953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '668cb56c328a'
down_revision = 'cc12ac692830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdns',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('access_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sources_domain', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(now())::timestamp(0) without time zone'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cdn_pkey')
    )
    op.drop_column('streams', 'cdn_id')
    op.add_column('streams', sa.Column('cdn_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('streams_cdn_id_fkey', 'streams', 'cdns', ['cdn_id'], ['id'])
    op.drop_column('streams', 'sources_domain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('streams_cdn_id_fkey', 'streams', type_='foreignkey')
    op.drop_column('streams', 'cdn_id')
    op.add_column('streams', sa.Column('cdn_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('streams', sa.Column('sources_domain', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('cdns')
    # ### end Alembic commands ###
