"""empty message

Revision ID: 81e0c44fc0c7
Revises: 446dc8f085a4
Create Date: 2018-01-25 21:56:35.416115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81e0c44fc0c7'
down_revision = '446dc8f085a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_schedule', sa.Column('course_number_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('class_schedule', sa.Column('subject_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('class_schedule_course_number_fkey', 'class_schedule', type_='foreignkey')
    op.drop_constraint('class_schedule_subject_fkey', 'class_schedule', type_='foreignkey')
    op.create_foreign_key('class_schedule_subject_id_fkey', 'class_schedule', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key('class_schedule_course_number_id_fkey', 'class_schedule', 'course_numbers', ['course_number_id'], ['id'])
    op.drop_column('class_schedule', 'subject')
    op.drop_column('class_schedule', 'course_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_schedule', sa.Column('course_number', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('class_schedule', sa.Column('subject', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('class_schedule_course_number_id_fkey', 'class_schedule', type_='foreignkey')
    op.drop_constraint('class_schedule_subject_id_fkey', 'class_schedule', type_='foreignkey')
    op.create_foreign_key('class_schedule_subject_fkey', 'class_schedule', 'subjects', ['subject'], ['id'])
    op.create_foreign_key('class_schedule_course_number_fkey', 'class_schedule', 'course_numbers', ['course_number'], ['id'])
    op.drop_column('class_schedule', 'subject_id')
    op.drop_column('class_schedule', 'course_number_id')
    # ### end Alembic commands ###
