"""empty message

Revision ID: cc12ac692830
Revises: 8c2cc9a50c35
Create Date: 2017-10-11 08:53:45.340441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc12ac692830'
down_revision = '8c2cc9a50c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streams',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cdn_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sources_domain', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(now())::timestamp(0) without time zone'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='streams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('listeners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('song', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connections', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stream_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(now())::timestamp(0) without time zone'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], name='listeners_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='listeners_pkey')
    )
    op.create_index('ix_listeners_song', 'listeners', ['song'], unique=False)
    op.create_table('sources',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('main', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stream_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(now())::timestamp(0) without time zone'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], name='sources_stream_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sources_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    op.drop_index('ix_listeners_song', table_name='listeners')
    op.drop_table('listeners')
    op.drop_table('streams')
    # ### end Alembic commands ###
